# Generated by Django 5.2.2 on 2025-06-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0539_ocrassociatedspecies_species_list_relates_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="deficiency_data",
        ),
        migrations.RemoveField(
            model_name="occurrencereport",
            name="deficiency_data",
        ),
    ]
