# Generated by Django 5.2.3 on 2025-06-12 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0541_speciesrole_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociatedSpeciesTaxonomy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "species_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="associated_species_taxonomy",
                        to="boranga.speciesrole",
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="associated_species_taxonomy",
                        to="boranga.taxonomy",
                    ),
                ),
            ],
        ),
    ]
