# Generated by Django 5.2.3 on 2025-06-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0542_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrassociatedspecies",
            name="related_species",
        ),
    ]
