# Generated by Django 5.2.3 on 2025-06-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0543_remove_ocrassociatedspecies_related_species_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrassociatedspecies",
            name="related_species",
            field=models.ManyToManyField(
                blank=True, to="boranga.associatedspeciestaxonomy"
            ),
        ),
    ]
