# Generated by Django 5.2.3 on 2025-06-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0545_alter_associatedspeciestaxonomy_taxonomy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occassociatedspecies",
            name="related_species",
        ),
    ]
