# Generated by Django 5.2.3 on 2025-06-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0546_remove_occassociatedspecies_related_species_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occassociatedspecies",
            name="related_species",
            field=models.ManyToManyField(
                blank=True, to="boranga.associatedspeciestaxonomy"
            ),
        ),
    ]
