# Generated by Django 5.2.3 on 2025-06-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0547_occassociatedspecies_related_species_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="lodgement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
