# Generated by Django 5.2.3 on 2025-06-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0548_occurrence_lodgement_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associatedspeciestaxonomy",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occanimalobservation",
            name="action_required",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="occanimalobservation",
            name="action_taken",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="occanimalobservation",
            name="distinctive_feature",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="occanimalobservation",
            name="observation_detail_comment",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="occassociatedspecies",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occconservationthreat",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="occcontactdetail",
            name="contact",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="occcontactdetail",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="occcontactdetail",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="occcontactdetail",
            name="organisation",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="occcontactdetail",
            name="role",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="occfirehistory",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="occhabitatcomposition",
            name="habitat_notes",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="occhabitatcomposition",
            name="water_quality",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="occidentification",
            name="barcode_number",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="occidentification",
            name="collector_number",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="occidentification",
            name="id_confirmed_by",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="occidentification",
            name="identification_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occidentification",
            name="permit_id",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="occlocation",
            name="boundary_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occlocation",
            name="locality",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occlocation",
            name="location_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occobservationdetail",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occplantcount",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="occurrencereport",
            name="assessor_data",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occurrencereport",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occurrencereport",
            name="record_source",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occurrencereport",
            name="site",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occvegetationstructure",
            name="vegetation_structure_layer_four",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occvegetationstructure",
            name="vegetation_structure_layer_one",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occvegetationstructure",
            name="vegetation_structure_layer_three",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="occvegetationstructure",
            name="vegetation_structure_layer_two",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocranimalobservation",
            name="action_required",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ocranimalobservation",
            name="action_taken",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ocranimalobservation",
            name="distinctive_feature",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ocranimalobservation",
            name="observation_detail_comment",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ocrassociatedspecies",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocrconservationthreat",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="ocrfirehistory",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ocrhabitatcomposition",
            name="habitat_notes",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ocrhabitatcomposition",
            name="water_quality",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="ocridentification",
            name="barcode_number",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="ocridentification",
            name="collector_number",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="ocridentification",
            name="id_confirmed_by",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ocridentification",
            name="identification_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocridentification",
            name="permit_id",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="ocrlocation",
            name="boundary_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocrlocation",
            name="locality",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocrlocation",
            name="location_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocrobservationdetail",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocrplantcount",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="ocrvegetationstructure",
            name="vegetation_structure_layer_four",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocrvegetationstructure",
            name="vegetation_structure_layer_one",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocrvegetationstructure",
            name="vegetation_structure_layer_three",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ocrvegetationstructure",
            name="vegetation_structure_layer_two",
            field=models.TextField(blank=True, default=""),
        ),
    ]
