# Generated by Django 5.2.3 on 2025-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0549_alter_associatedspeciestaxonomy_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencereportapprovaldetails",
            name="details",
            field=models.TextField(blank=True, default=""),
        ),
    ]
