# Generated by Django 5.2.3 on 2025-06-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0550_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occplantcount",
            name="detailed_alive_unknown",
        ),
        migrations.RemoveField(
            model_name="occplantcount",
            name="detailed_dead_unknown",
        ),
        migrations.RemoveField(
            model_name="ocrplantcount",
            name="detailed_alive_unknown",
        ),
        migrations.RemoveField(
            model_name="ocrplantcount",
            name="detailed_dead_unknown",
        ),
    ]
