# Generated by Django 5.2.3 on 2025-06-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0551_remove_occplantcount_detailed_alive_unknown_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="occanimalobservation",
            old_name="observation_detail_comment",
            new_name="animal_observation_detail_comment",
        ),
        migrations.RenameField(
            model_name="ocranimalobservation",
            old_name="observation_detail_comment",
            new_name="animal_observation_detail_comment",
        ),
    ]
