# Generated by Django 5.2.3 on 2025-06-25 07:47

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import boranga.components.users.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0551_remove_occplantcount_detailed_alive_unknown_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occanimalobservation',
            old_name='observation_detail_comment',
            new_name='animal_observation_detail_comment',
        ),
        migrations.RenameField(
            model_name='ocranimalobservation',
            old_name='observation_detail_comment',
            new_name='animal_observation_detail_comment',
        ),
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default='None', max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.species_and_communities.models.update_community_doc_filename),
        ),
        migrations.AlterField(
            model_name='communitylogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.species_and_communities.models.update_community_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='conservationstatusamendmentrequestdocument',
            name='_file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.conservation_status.models.update_conservation_status_amendment_request_doc_filename),
        ),
        migrations.AlterField(
            model_name='conservationstatusdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.conservation_status.models.update_conservation_status_doc_filename),
        ),
        migrations.AlterField(
            model_name='conservationstatuslogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.conservation_status.models.update_conservation_status_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='emailuserlogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.users.models.email_user_comms_log_document_upload_location),
        ),
        migrations.AlterField(
            model_name='meetinglogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.meetings.models.update_meeting_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='_file',
            field=models.FileField(default='None', max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.meetings.models.update_meeting_doc_filename),
        ),
        migrations.AlterField(
            model_name='occurrencedocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_doc_filename),
        ),
        migrations.AlterField(
            model_name='occurrencelogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='occurrencereportamendmentrequestdocument',
            name='_file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_amendment_request_doc_filename),
        ),
        migrations.AlterField(
            model_name='occurrencereportbulkimporttask',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_path, validators=[boranga.components.occurrence.models.validate_bulk_import_file_extension]),
        ),
        migrations.AlterField(
            model_name='occurrencereportdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_doc_filename),
        ),
        migrations.AlterField(
            model_name='occurrencereportlogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='occurrencereportshapefiledocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_doc_filename),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='_file',
            field=models.FileField(default='None', max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.species_and_communities.models.update_species_doc_filename),
        ),
        migrations.AlterField(
            model_name='specieslogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/oak/dev/boranga/private-media/'), upload_to=boranga.components.species_and_communities.models.update_species_comms_log_filename),
        ),
    ]
