# Generated by Django 5.2.3 on 2025-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0552_rename_observation_detail_comment_occanimalobservation_animal_observation_detail_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="occplantcount",
            name="individual_quadrat_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ocrplantcount",
            name="individual_quadrat_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
