# Generated by Django 5.2.3 on 2025-06-26 03:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0553_alter_occplantcount_individual_quadrat_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occobservationdetail",
            name="area_surveyed",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=Decimal("0.0000"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="ocrobservationdetail",
            name="area_surveyed",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=Decimal("0.0000"), max_digits=14
            ),
        ),
    ]
