# Generated by Django 5.2.3 on 2025-06-26 04:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0554_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occobservationdetail",
            name="area_surveyed",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=14,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ocrobservationdetail",
            name="area_surveyed",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=14,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000"))
                ],
            ),
        ),
    ]
