# Generated by Django 5.2.3 on 2025-06-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0558_animalbehaviour_areaassessment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occanimalobservation",
            name="animal_behaviour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boranga.animalbehaviour",
            ),
        ),
        migrations.AddField(
            model_name="occobservationdetail",
            name="area_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boranga.areaassessment",
            ),
        ),
        migrations.AddField(
            model_name="ocranimalobservation",
            name="animal_behaviour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boranga.animalbehaviour",
            ),
        ),
        migrations.AddField(
            model_name="ocrobservationdetail",
            name="area_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boranga.areaassessment",
            ),
        ),
    ]
