# Generated by Django 5.2.3 on 2025-06-30 03:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0559_occanimalobservation_animal_behaviour_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalbehaviour",
            options={
                "ordering": ("order",),
                "verbose_name": "Animal Behaviour",
                "verbose_name_plural": "Animal Behaviours",
            },
        ),
        migrations.AlterModelOptions(
            name="areaassessment",
            options={
                "ordering": ("order",),
                "verbose_name": "Area Assessment",
                "verbose_name_plural": "Area Assessments",
            },
        ),
        migrations.AlterField(
            model_name="occanimalobservation",
            name="reproductive_state",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[], max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ocranimalobservation",
            name="reproductive_state",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[], max_length=250, null=True
            ),
        ),
    ]
