# Generated by Django 5.2.3 on 2025-07-02 01:18

import boranga.components.main.models
import boranga.components.occurrence.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0560_alter_animalbehaviour_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceShapefileDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "_file",
                    models.FileField(
                        max_length=512,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/private-media/",
                            location="/home/oak/dev/boranga/private-media/",
                        ),
                        upload_to=boranga.components.occurrence.models.update_occurrence_report_doc_filename,
                    ),
                ),
                ("input_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occurrence_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shapefile_documents",
                        to="boranga.occurrence",
                    ),
                ),
            ],
            bases=(
                boranga.components.main.models.Nh3SanitizationModelMixin,
                models.Model,
            ),
        ),
    ]
