# Generated by Django 5.2.3 on 2025-07-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0562_rename_occurrence_report_occurrenceshapefiledocument_occurrence_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committeemembers",
            options={
                "ordering": ("order",),
                "verbose_name": "Committee Member",
                "verbose_name_plural": "Committee Members",
            },
        ),
        migrations.AlterField(
            model_name="occurrencetenure",
            name="significant_to_occurrence",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
