# Generated by Django 5.2.3 on 2025-07-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0563_alter_committeemembers_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationstatusissuanceapprovaldetails",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
