# Generated by Django 5.2.3 on 2025-07-07 03:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0565_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buffergeometry",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, extent=(112.9, -35.0, 129.0, -13.5), null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="occurrencegeometry",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, extent=(112.9, -35.0, 129.0, -13.5), null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="occurrencereportgeometry",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, extent=(112.9, -35.0, 129.0, -13.5), null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="occurrencesite",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, extent=(112.9, -35.0, 129.0, -13.5), null=True, srid=4326
            ),
        ),
    ]
