# Generated by Django 5.2.4 on 2025-07-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0567_alter_buffergeometry_geometry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
