# Generated by Django 5.2.4 on 2025-07-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0568_conservationstatus_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationstatus",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="Whether the record is locked"
            ),
        ),
    ]
