# Generated by Django 5.2.4 on 2025-07-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    def lock_conservation_status_records(apps, schema_editor):
        ConservationStatus = apps.get_model("boranga", "ConservationStatus")
        ConservationStatus.objects.filter(
            processing_status__in=[
                "approved",
                "closed",
                "delisted",
                "declined",
            ]
        ).update(locked=True)

    dependencies = [
        ("boranga", "0569_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RunPython(
            lock_conservation_status_records, reverse_code=migrations.RunPython.noop
        ),
    ]
