# Generated by Django 5.2.4 on 2025-07-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    def revert_processing_status_unlocked_cs(apps, schema_editor):
        ConservationStatus = apps.get_model("boranga", "ConservationStatus")
        for cs in ConservationStatus.objects.filter(
            processing_status="unlocked",
        ):
            cs.processing_status = cs.prev_processing_status
            cs.prev_processing_status = None
            cs.save(update_fields=["processing_status", "prev_processing_status"])

    dependencies = [
        ("boranga", "0570_lock_conservation_status_records"),
    ]

    operations = [
        migrations.RunPython(
            revert_processing_status_unlocked_cs,
            migrations.RunPython.noop,
        ),
    ]
