# Generated by Django 5.2.4 on 2025-07-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0571_revert_processing_status_unlocked_cs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="prev_processing_status",
        ),
        migrations.AlterField(
            model_name="conservationstatus",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("discarded", "Discarded"),
                    ("with_assessor", "With Assessor"),
                    ("with_referral", "With Referral"),
                    ("deferred", "Deferred"),
                    ("proposed_for_agenda", "Proposed For Agenda"),
                    ("ready_for_agenda", "Ready For Agenda"),
                    ("on_agenda", "On Agenda"),
                    ("with_approver", "Proposed DeListed"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("delisted", "DeListed"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Processing Status",
            ),
        ),
    ]
