# Generated by Django 5.2.4 on 2025-07-09 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0572_remove_conservationstatus_prev_processing_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conservationstatus",
            name="datetime_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
