# Generated by Django 5.2.4 on 2025-07-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0574_rename_created_date_occurrence_datetime_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
