# Generated by Django 5.2.4 on 2025-07-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0575_occurrence_locked_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="Whether the record is locked"
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("split", "Split"),
                    ("combine", "Combine"),
                    ("historical", "Historical"),
                    ("discarded", "Discarded"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Processing Status",
            ),
        ),
    ]
