# Generated by Django 5.2.4 on 2025-07-18 02:45

import boranga.components.occurrence.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0576_alter_communitydocument__file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='communitylogdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conservationstatusamendmentrequestdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conservationstatusdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conservationstatuslogdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emailuserlogdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meetinglogdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='occurrencelogdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='occurrencereportamendmentrequestdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='occurrencereportlogdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='occurrencereportshapefiledocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='occurrenceshapefiledocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciesdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='specieslogdocument',
            name='uploaded_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='occurrencereportbulkimporttask',
            name='_associated_files_zip',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_associated_files_path, validators=[boranga.components.occurrence.models.validate_bulk_import_associated_files_extension]),
        ),
        migrations.AlterField(
            model_name='occurrencereportbulkimporttask',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_path, validators=[boranga.components.occurrence.models.validate_bulk_import_file_extension]),
        ),
        migrations.AlterField(
            model_name='occurrenceshapefiledocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_doc_filename),
        ),
    ]
