# Generated by Django 5.2.4 on 2025-07-22 08:18

import boranga.components.main.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0578_alter_communitydistribution_community_original_area_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FloraGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[,]",
                                code="comma_not_allowed",
                                inverse_match=True,
                                message="Commas not allowed in the display field for a django lookup.",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Flora Group",
                "verbose_name_plural": "Flora Groups",
                "ordering": ["order"],
            },
            bases=(
                boranga.components.main.models.Nh3SanitizationModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="FloraSubGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[,]",
                                code="comma_not_allowed",
                                inverse_match=True,
                                message="Commas not allowed in the display field for a django lookup.",
                            )
                        ],
                    ),
                ),
                (
                    "flora_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_groups",
                        to="boranga.floragroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flora Sub Group",
                "verbose_name_plural": "Flora Sub Groups",
                "ordering": ["flora_group", "order"],
            },
            bases=(
                boranga.components.main.models.Nh3SanitizationModelMixin,
                models.Model,
            ),
        ),
    ]
