# Generated by Django 5.2.4 on 2025-07-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0579_floragroup_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FloraGroup",
            new_name="FaunaGroup",
        ),
        migrations.RenameModel(
            old_name="FloraSubGroup",
            new_name="FaunaSubGroup",
        ),
        migrations.AlterModelOptions(
            name="faunagroup",
            options={
                "ordering": ["order"],
                "verbose_name": "Fauna Group",
                "verbose_name_plural": "Fauna Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="faunasubgroup",
            options={
                "ordering": ["fauna_group", "order"],
                "verbose_name": "Fauna Sub Group",
                "verbose_name_plural": "Fauna Sub Groups",
            },
        ),
        migrations.RenameField(
            model_name="faunasubgroup",
            old_name="flora_group",
            new_name="fauna_group",
        ),
    ]
