# Generated by Django 5.2.4 on 2025-07-28 04:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0581_species_fauna_group_species_fauna_sub_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitydistribution",
            name="extent_of_occurrences",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="speciesdistribution",
            name="extent_of_occurrences",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
