# Generated by Django 5.2.4 on 2025-07-29 03:17

from django.db import migrations, models
from django.db.models.functions import Replace


def rename_ocr_to_orf(apps, schema_editor):
    OccurrenceReport = apps.get_model("boranga", "OccurrenceReport")
    OccurrenceReport.objects.filter(occurrence_report_number__startswith="OCR").update(
        occurrence_report_number=Replace(
            models.F("occurrence_report_number"),
            models.Value("OCR"),
            models.Value("ORF"),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0582_alter_communitydistribution_extent_of_occurrences_and_more"),
    ]

    operations = [
        migrations.RunPython(rename_ocr_to_orf),
    ]
