# Generated by Django 5.2.5 on 2025-08-12 07:01

import django.core.validators
import multiselectfield.db.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0583_rename_ocr_to_orf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="occurrence_source",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("ocr", "ORF"), ("non-ocr", "Non-ORF (describe in comments)")],
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="speciesdistribution",
            name="extent_of_occurrences",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
