# Generated by Django 5.2.5 on 2025-08-12 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0584_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencetenure",
            name="datetime_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
