# Generated by Django 5.2.5 on 2025-08-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0585_alter_communitydocument__file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrencereportbulkimportschema',
            options={'ordering': ['group_type', '-version'], 'verbose_name': 'Occurrence Report Form Bulk Import Schema', 'verbose_name_plural': 'Occurrence Report Form Bulk Import Schemas'},
        ),
        migrations.AlterModelOptions(
            name='occurrencereportbulkimportschemacolumn',
            options={'ordering': ['schema', 'order'], 'verbose_name': 'Occurrence Report Form Bulk Import Schema Column', 'verbose_name_plural': 'Occurrence Report Form Bulk Import Schema Columns'},
        ),
    ]
