# Generated by Django 5.2.5 on 2025-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0586_alter_occurrencereportbulkimportschema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='migrated_from_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='species',
            name='migrated_from_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
