# Generated by Django 5.2.5 on 2025-08-20 07:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0587_community_migrated_from_id_species_migrated_from_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occplantcount',
            name='estimated_population_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ocrplantcount',
            name='estimated_population_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
