# Generated by Django 5.2.5 on 2025-08-26 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0588_alter_communitydocument__file_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyValueMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_system', models.CharField(max_length=30)),
                ('list_name', models.CharField(max_length=50)),
                ('legacy_value', models.CharField(max_length=255)),
                ('canonical_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['legacy_system', 'list_name'], name='boranga_leg_legacy__8a1ac8_idx'), models.Index(fields=['legacy_system', 'list_name', 'legacy_value'], name='boranga_leg_legacy__0898db_idx')],
                'unique_together': {('legacy_system', 'list_name', 'legacy_value')},
            },
        ),
    ]
