# Generated by Django 5.2.11 on 2026-02-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boranga", "0624_make_name_unique_per_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencegeometry",
            name="buffer_radius",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
