# Generated by Django 5.2.11 on 2026-02-19 05:04

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import boranga.components.users.models
import boranga.utils.uploads
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0624_make_name_unique_per_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_community_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='communitylogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_community_comms_log_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='conservationstatusamendmentrequestdocument',
            name='_file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.conservation_status.models.update_conservation_status_amendment_request_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='conservationstatusdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.conservation_status.models.update_conservation_status_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='conservationstatuslogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.conservation_status.models.update_conservation_status_comms_log_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='emailuserlogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.components.users.models.email_user_comms_log_document_upload_location),
        ),
        migrations.AlterField(
            model_name='meetinglogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.meetings.models.update_meeting_comms_log_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.meetings.models.update_meeting_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occurrencedocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.occurrence.models.update_occurrence_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occurrencegeometry',
            name='buffer_radius',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='occurrencelogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.occurrence.models.update_occurrence_comms_log_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occurrencereportamendmentrequestdocument',
            name='_file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.occurrence.models.update_occurrence_report_amendment_request_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occurrencereportbulkimporttask',
            name='_associated_files_zip',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_associated_files_path, validators=[boranga.components.occurrence.models.validate_bulk_import_associated_files_extension]),
        ),
        migrations.AlterField(
            model_name='occurrencereportbulkimporttask',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_path, validators=[boranga.components.occurrence.models.validate_bulk_import_file_extension]),
        ),
        migrations.AlterField(
            model_name='occurrencereportdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.occurrence.models.update_occurrence_report_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occurrencereportlogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.occurrence.models.update_occurrence_report_comms_log_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='occurrencereportshapefiledocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_shapefile_doc_filename),
        ),
        migrations.AlterField(
            model_name='occurrenceshapefiledocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_shapefile_doc_filename),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='_file',
            field=models.FileField(default=None, max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_species_doc_filename, None, True)),
        ),
        migrations.AlterField(
            model_name='specieslogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga.worktrees/copilot-worktree-2026-02-19T04-43-45/private-media/'), upload_to=boranga.utils.uploads.RandomizeUploadTo(boranga.components.species_and_communities.models.update_species_comms_log_filename, None, True)),
        ),
    ]
