# Generated by Django 5.2.11 on 2026-02-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0625_change_buffer_radius_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationstatus',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('ready_for_agenda', 'In Meeting'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'Delisted')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='conservationstatus',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('discarded', 'Discarded'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('deferred', 'Deferred'), ('proposed_for_agenda', 'Proposed For Agenda'), ('ready_for_agenda', 'Ready For Agenda'), ('on_agenda', 'On Agenda'), ('with_approver', 'Proposed Delisted'), ('approved', 'Approved'), ('declined', 'Declined'), ('delisted', 'Delisted'), ('closed', 'Closed')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='occurrencereport',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('with_approver', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'Delisted')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='occurrencereport',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('approved', 'Approved'), ('declined', 'Declined'), ('unlocked', 'Unlocked'), ('discarded', 'Discarded'), ('closed', 'Delisted')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
    ]
