# Generated by Django 5.2.11 on 2026-02-24 09:02

import boranga.components.meetings.models
import boranga.components.species_and_communities.models
import boranga.utils.uploads
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0626_alter_communitydocument__file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occhabitatcomposition',
            name='habitat_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='occplantcount',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
