# Generated by Django 5.2.11 on 2026-02-26 02:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0628_expand_gis_extent_for_cocos_and_kimberley'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffergeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='occurrencegeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='occurrencesite',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(95.0, -38.5, 129.1, -9.0), null=True, srid=4326),
        ),
    ]
