# Generated by Django 5.2.11 on 2026-03-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0629_expand_gis_extent_christmas_island'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrhabitatcomposition',
            name='habitat_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ocrplantcount',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
