# Generated by Django 5.2.11 on 2026-03-11 03:39

import boranga.components.meetings.models
import boranga.components.species_and_communities.models
import boranga.utils.uploads
import django.core.files.storage
from django.db import migrations, models


def backfill_datetime_approved(apps, schema_editor):
    """Backfill datetime_approved from the action log for existing approved records."""
    OccurrenceReport = apps.get_model("boranga", "OccurrenceReport")
    OccurrenceReportUserAction = apps.get_model("boranga", "OccurrenceReportUserAction")

    approved_reports = OccurrenceReport.objects.filter(
        processing_status="approved",
        datetime_approved__isnull=True,
    )
    for report in approved_reports.iterator():
        action = (
            OccurrenceReportUserAction.objects.filter(
                occurrence_report_id=report.pk,
                what__icontains="has been approved by",
            )
            .order_by("when")
            .last()
        )
        if action:
            OccurrenceReport.objects.filter(pk=report.pk).update(
                datetime_approved=action.when
            )


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0630_alter_ocr_habitat_notes_and_plant_count_comment_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereport",
            name="datetime_approved",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_datetime_approved,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="communitydocument",
            name="_file",
            field=models.FileField(
                default=None,
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/data/data/projects/boranga/private-media/",
                ),
                upload_to=boranga.utils.uploads.RandomizeUploadTo(
                    boranga.components.species_and_communities.models.update_community_doc_filename,
                    None,
                    True,
                ),
            ),
        ),
        migrations.AlterField(
            model_name="minutes",
            name="_file",
            field=models.FileField(
                default=None,
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/data/data/projects/boranga/private-media/",
                ),
                upload_to=boranga.utils.uploads.RandomizeUploadTo(
                    boranga.components.meetings.models.update_meeting_doc_filename,
                    None,
                    True,
                ),
            ),
        ),
        migrations.AlterField(
            model_name="speciesdocument",
            name="_file",
            field=models.FileField(
                default=None,
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/data/data/projects/boranga/private-media/",
                ),
                upload_to=boranga.utils.uploads.RandomizeUploadTo(
                    boranga.components.species_and_communities.models.update_species_doc_filename,
                    None,
                    True,
                ),
            ),
        ),
    ]
