# Generated by Django 5.2.11 on 2026-03-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0633_add_last_modified_by_to_occurrence_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occanimalobservation',
            name='distinctive_feature',
        ),
        migrations.RemoveField(
            model_name='ocranimalobservation',
            name='distinctive_feature',
        ),
    ]
