# Generated by Django 5.2.11 on 2026-03-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0634_remove_distinctive_feature_from_animal_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoserverurl',
            name='wms_version',
        ),
    ]
